import pyautogui
import time

pyautogui.PAUSE = 0.3
pyautogui.FAILSAFE = True

pyautogui.moveTo(1233, 896)
pyautogui.click()
pyautogui.hotkey('shift', 'f5')  
pyautogui.moveTo(1233, 89)
pyautogui.click()
pyautogui.hotkey('ctrl', 'f2')
pyautogui.click()
pyautogui.hotkey('ctrl', 'f3')
pyautogui.click()
pyautogui.hotkey('ctrl', 'f12')  
# pyautogui.click()
pyautogui.hotkey('ctrl', 'f11')  
pyautogui.click()
pyautogui.hotkey('ctrl', 'f10')  
pyautogui.click()
pyautogui.hotkey('ctrl', 'f5')  
pyautogui.click()
pyautogui.hotkey('ctrl', 'f8')  
pyautogui.click()
pyautogui.hotkey('ctrl', 'f7')  
pyautogui.click()
pyautogui.hotkey('ctrl', 'f6')  
pyautogui.click()
pyautogui.hotkey('ctrl', 'f9')  
pyautogui.click()
pyautogui.hotkey('ctrl', 'f4')  
# pyautogui.click()
pyautogui.hotkey('ctrl', 'f1')  
pyautogui.click()
pyautogui.hotkey('shift', 'f12')  
pyautogui.click()
pyautogui.hotkey('shift', 'f11')  
pyautogui.click()
pyautogui.hotkey('shift', 'f10')  
pyautogui.click()
pyautogui.hotkey('shift', 'f9')  
pyautogui.click()
pyautogui.hotkey('shift', 'f8')  
# pyautogui.click()
pyautogui.hotkey('shift', 'f7')  
pyautogui.click()
pyautogui.hotkey('shift', 'f6')  
pyautogui.click()
pyautogui.hotkey('shift', 'f4')  
pyautogui.click()
pyautogui.hotkey('shift', 'f3')  
# pyautogui.click()
pyautogui.hotkey('f8')  
pyautogui.click()
pyautogui.hotkey('f10')  
pyautogui.click()
pyautogui.hotkey('f7')  
pyautogui.click()
pyautogui.hotkey('f6')  
# pyautogui.click()
pyautogui.hotkey('f12')  
# pyautogui.click()
time.sleep(0.3)